Add few important links
fortran-lang/fpm pull request #414
Opened 2021-03-26 20:48 UTC by ChetanKarwa

I have addressed some of the feedbacks which were acknowledged by the reviewers.
- [Suggestion from Laurence](https://github.com/fortran-lang/fpm/pull/402#pullrequestreview-616528386)
- [Suggestion from Sebastian](https://github.com/fortran-lang/fpm/pull/402#pullrequestreview-616539343)
- [Suggestion from Jon](https://github.com/fortran-lang/fpm/pull/402#issuecomment-802931356)

2021-03-26 21:35 UTC, milancurcic requested changes
Looks good, thanks! I left two requests for changes.

2021-03-26 21:35 UTC, milancurcic commented on README.md
> +Fpm's user interface is modeled after [Rust's Cargo](https://doc.rust-lang.org/cargo/) ([Github Repo](https://github.com/rust-lang/cargo)),
No need to point also to the GH repo

```suggestion
Fpm's user interface is modeled after [Rust's Cargo](https://doc.rust-lang.org/cargo/),
```

2021-03-26 21:35 UTC, milancurcic commented on README.md
> +[Contributor Guide](CONTRIBUTING.md). You can also discuss your ideas and queries with the community on [Fortran-Lang Discourse](https://fortran-lang.discourse.group/)
I believe in the original suggestion, @awvwgk meant the fpm Discussions board, but good to mention both that and the Discourse.

```suggestion
[Contributor Guide](CONTRIBUTING.md). You can also discuss your ideas and queries with the community in [fpm discussions](https://github.com/fortran-lang/fpm/discussions), or more broadly on [Fortran-Lang Discourse](https://fortran-lang.discourse.group/)
```

2021-03-27 16:21 UTC, LKedward reviewed
Thanks @ChetanKarwa! With Milan's suggestions this looks good to me :+1:

2021-03-27 17:42 UTC, ChetanKarwa commented
I have made the requested changes. It's good to go now.

2021-03-27 19:15 UTC, milancurcic approved these changes
Thank you, @ChetanKarwa

2021-03-27 19:16 UTC, merged