docs: simplify & update README
fortran-lang/fpm pull request #778
Opened 2022-10-12 16:13 UTC by gnikit

- Added multiple links to the FPM webpage, homepage,
  downloading instructions and Getting started and tutorials
- Removed most of the install instructions and redirected to website
- Removed bootstrapping instructions
- Added fpm logo with hyperlink in README
- Fixed link to Manifest in README

Fixes Link to documentation in README #776

2022-10-12 16:26 UTC, milancurcic requested changes
If you remove some install instructions but keep others, then the ones you keep implicitly become the recommended ones. Do we really recommend Conda as the best way to get fpm? That requires having and using yet another tool. I think it's okay to keep the Conda and Homebrew instructions, but at the very least also keep and recommend the link to the binary release downloads, as that's the easiest way to get fpm without assuming a 3rd party package manager.

Other changes look good!

2022-10-12 16:44 UTC, gnikit commented
@milancurcic Thanks for the quick turnaround in this PR. I agree I was actually meant to include them first but I somehow forgot. I think we might need to do some edits on the fpm-docs repo as well. Specifically, I would suggest:

- moving "Installing fpm" (https://fpm.fortran-lang.org/en/how-to/installation.html) at the very top the TOC on the left and outside "How To"
- Remove the "Design Documents" card from the homepage and add an "Install fpm" card. The order of the cards being from left to right, top to bottom (1. "Install fpm", 2. "Tutorials", 3. "How-To Guides" (now empty), 4. "References")

2022-10-27 14:00 UTC, gnikit commented
Please CC anyone else that should review this. Remember to check accompanying PR https://github.com/fortran-lang/fpm-docs/pull/87

2022-10-27 14:21 UTC, milancurcic approved these changes
I think it's good to go, thanks!

2022-10-27 14:37 UTC, LKedward approved these changes
Thanks @gnikit, this is a really nice improvement!

2022-10-27 15:13 UTC, gnikit commented on README.md
> +**Follow our [Quickstart Tutorial](https://fpm.fortran-lang.org/en/tutorial/hello-fpm.html) to get familiar with fpm**.
No, just personal taste to point the user to the next step. I can remove it if you want.

2022-10-29 09:29 UTC, merged