Add support for toggling Fortran features
fortran-lang/fpm pull request #864
Opened 2023-04-02 08:17 UTC by awvwgk

This has been hanging around stale long enough, here is a draft implementation for disabling implicit typing and external interfaces by default with opt-in toggles on per package basis.

*Usage*

```toml
[fortran]
implicit-typing = true  # default: false
implicit-external = true  # default: false
```

Closes #577

2023-04-02 17:55 UTC, gnikit requested changes
Very nice you beat me to it (by many, many hours). I left some comments/patch suggestions for adding support for the other compilers (at least for the fixed/free flag). Have a look and let me know if they are correct, if not you can dismiss them.

2023-04-02 17:55 UTC, gnikit commented on src/fpm_compiler.F90
> +    flag_gnu_fixed_format = " -ffixed-form"
I would add the other compiler options too (sorry couldn't think of another way of doing it through the _patch suggestion_


```suggestion
    flag_gnu_fixed_format = " -ffixed-form"

character(*), parameter :: &
    flag_pgi_backslash = " -Mbackslash", &
    flag_pgi_traceback = " -traceback", &
    flag_pgi_debug = " -g", &
    flag_pgi_check = " -Mbounds -Mchkptr -Mchkstk", &
    flag_pgi_warn = " -Minform=inform", &
    flag_pgi_free_format = " -Mfree", &
    flag_pgi_fixed_format = " -Mfixed"

character(*), parameter :: &
    flag_ibmxl_backslash = " -qnoescape"

character(*), parameter :: &
    flag_intel_backtrace = " -traceback", &
    flag_intel_warn = " -warn all", &
    flag_intel_check = " -check all", &
    flag_intel_debug = " -O0 -g", &
    flag_intel_fp = " -fp-model precise -pc64", &
    flag_intel_align = " -align all", &
    flag_intel_limit = " -error-limit 1", &
    flag_intel_pthread = " -reentrancy threaded", &
    flag_intel_nogen = " -nogen-interfaces", &
    flag_intel_byterecl = " -assume byterecl", &
    flag_intel_free_format = " -free", &
    flag_intel_fixed_format = " -fixed"

character(*), parameter :: &
    flag_intel_backtrace_win = " /traceback", &
    flag_intel_warn_win = " /warn:all", &
    flag_intel_check_win = " /check:all", &
    flag_intel_debug_win = " /Od /Z7", &
    flag_intel_fp_win = " /fp:precise", &
    flag_intel_align_win = " /align:all", &
    flag_intel_limit_win = " /error-limit:1", &
    flag_intel_pthread_win = " /reentrancy:threaded", &
    flag_intel_nogen_win = " /nogen-interfaces", &
    flag_intel_byterecl_win = " /assume:byterecl", &
    flag_intel_free_format_win = " /free", &
    flag_intel_fixed_format_win = " /fixed"

character(*), parameter :: &
    flag_nag_coarray = " -coarray=single", &
    flag_nag_pic = " -PIC", &
    flag_nag_check = " -C", &
    flag_nag_debug = " -g -O0", &
    flag_nag_opt = " -O4", &
    flag_nag_backtrace = " -gline", &
    flag_nag_free_format = " -free", &
    flag_nag_fixed_format = " -fixed"

```

2023-04-02 17:55 UTC, gnikit commented on src/fpm_compiler.F90
> +
Adds free-form compiler flags. I think the grouped ids per `case` are correct but please double check

```suggestion
       case(id_caf, id_gcc, id_f95, id_flang_new)
           flags = flag_gnu_free_format

        case(id_intel_classic_nix, id_intel_llvm_nix, id_intel_classic_mac)
            flags = flag_intel_free_format

        case(id_intel_classic_windows, id_intel_llvm_windows)
            flags = flag_intel_free_format_win

        case(id_pgi, id_nvhpc, id_flang, id_f18)
            flags = flag_pgi_free_format

        case(id_nag)
            flags = flag_nag_free_format

```

2023-04-02 17:55 UTC, gnikit commented on src/fpm_compiler.F90
> +
Adds fixed-form compile flags (also fixes indentation on the fist couple of lines)

```suggestion
        select case(self%id)
        case(id_caf, id_gcc, id_f95, id_flang_new)
           flags = flag_gnu_fixed_format

        case(id_intel_classic_nix, id_intel_llvm_nix, id_intel_classic_mac)
            flags = flag_intel_fixed_format

        case(id_intel_classic_windows, id_intel_llvm_windows)
            flags = flag_intel_fixed_format_win

        case(id_pgi, id_nvhpc, id_flang, id_f18)
            flags = flag_pgi_fixed_format

        case(id_nag)
            flags = flag_nag_fixed_format

```

2023-04-02 20:01 UTC, awvwgk commented
Giannis @gnikit, feel free to commit the changes directly to my branch.

2023-04-03 09:41 UTC, gnikit commented
> Giannis @gnikit, feel free to commit the changes directly to my branch.

Will do this today

2023-04-03 15:15 UTC, milancurcic commented
I think this is a great change. 

The TOML key should be `source-form`, not `source-format`. Likewise, use "fixed-form" and "free-form" instead of "fixed-format" and "free-format" in example names.

`"default"` for the `source-form` makes sense to me--it reads like "use the compiler default, whatever that is".

2023-04-07 07:52 UTC, awvwgk commented
Thanks everyone for reviewing and providing feedback. While not all compilers currently support these features, we can add those in the future as we discover the correct options. I'll go ahead and merge now.

2023-04-07 07:53 UTC, merged