Only update dependencies between cached build and manifest
fortran-lang/fpm pull request #871
Opened 2023-04-07 18:59 UTC by perazz

Addressing #870. 

This update restricts the dependency update to the comparison between a _cached build_ (i.e., cache.toml) and the manifest. This still addresses the issue #837 which originated #843, but solves #870, i.e., dependencies are not replaced/marked for update when duplicates are found down the dependency tree. 

@everythingfunctional please let me know if this is the intended behavior.
@awvwgk @certik @minhqdao I would like to also kindly request your opinions especially as far as how this behavior should fit into the upcoming version constraint resolution mechanism. 

Happy Easter everyone!

2023-04-07 19:37 UTC, everythingfunctional approved these changes
Thanks for the quick fix on this. It looks reasonable to me, and I gave it a quick test with my project and seems to fix the problem.

2023-04-07 20:05 UTC, everythingfunctional requested changes
I take back my previous statement. On subsequent builds, it still tries to "update" dependencies to the incorrect ones.

2023-04-07 20:22 UTC, perazz commented
After some debugging, the `git` descriptor should be `tag` but is instead a `sha1`: 

```
# Dependency ! cached
# - name                     jonquil
# - kind                     git
# Git target
# - URL                      https://github.com/toml-f/jonquil
# - sha1                     v0.2.0
# Dependency ! manifest
# - name                     jonquil
# - kind                     git
# Git target
# - URL                      https://github.com/toml-f/jonquil
# - tag                      v0.2.0

```

I need to look further, as it seems like the problem may be elsewhere.

2023-04-08 05:18 UTC, perazz commented
Thank you @everythingfunctional, I've looked into this a bit further before leaving for Easter. The fpm logic is to 
1) load the cached dependency tree from cached.toml (-> was tree-sorted already)
2) add manifest dependencies (-> not yet sorted)

With this logic there is no reliable way to check if  manifest dependencies should be updated, because we don't know what comes next (they are unsorted: duplicates present). The current implementation is safe in that it gets the right version from fpm.toml, but sometimes it requests for updates more often than necessary. 

I propose checking cached dependencies _after_ the manifest tree is first fully built: 
1) build full dependency tree (assume no cache) 
2) search in the cached deps, if some cached dependencies are the same, don't update them

This is the only way the model can fully build the _requested_ dependency tree with its constraints, then check what's in the cache to avoid downloading repos again. I believe this logic will also be needed for the version constraint resolution later. the CI is OK but please let me know if this now achieves the right behavior for your cases, plus when I'm back I will start thinking of new test cases

2023-04-08 13:58 UTC, urbanjost commented
It should be kept in mind that fpm should be able to operate on a machine with no network connection and except for using git as a substitute for curl or wget be able to work without git.

2023-04-08 14:59 UTC, urbanjost commented
Double-checking I am building the right version, as seeing no change. Almost every project with a dependency updates on essentially every fpm command; in several cases this means several minutes per command. Essentially unusable.  Wanted to do more 0.8.0 testing but it looks like I build the right PR.  An early suggestion to create a module in build/ that optionally could be used for a program that included the git ID when available would be so much nicer as you could tell exactly which version was used and it would change automatically.

2023-04-08 16:07 UTC, perazz commented
Thank you @urbanjost for testing - please post as many examples as you can,  where you see updates that should not be; I will address as soon as possible

2023-04-08 23:40 UTC, urbanjost commented
a stress test for version 0.7.0 is contained in 

wget http://www.urbanjost.altervista.org/REMOVE/urbanjost7.tgz

which I am converting to do basically the same test for 0.8.0;  the PR log and ID match but as far as I see so far everyone with a remote dependency rebuilds and "fpm test" causes everything to update even if everything is built with "fpm build". 

I cleared everything out, and using a new fpm command I built from PR871 that I changed so "fpm version" shows a captured git ID and see
```text
$ fpm --version
Version:     0.8.0, alpha
Program:     fpm(1)
Description: A Fortran package manager and build system
Home Page:   https://github.com/fortran-lang/fpm
License:     MIT
GitID:       1d5a8282e41dbfefd3cb45f4a50175ec0c021093
```
and I get an update of everything with every fpm command.  Will try again in a few days and see if I am fat-fingering something; will probably not be able to till Tues. though.

2023-04-09 05:50 UTC, perazz commented
Much appreciated @urbanjost, thank you - unfortunately I’m also unable to work on it until Tues but will address your stress tests as soon as am back

2023-04-10 14:49 UTC, everythingfunctional approved these changes
It looks like this is behaving correctly. The right dependency versions are selected even when rebuilding. However, it reporting that it is re-initialising every dependency on every rebuild is a bit obnoxious. I much prefer a little noise to incorrect behavior though, so I'm fine with accepting this for now and fixing that part later (so long as later isn't too much later).

2023-04-10 14:57 UTC, awvwgk approved these changes
Thanks for the quick fix. I agree with Brad that we need a follow-up patch for this, but it is important enough to merge quickly and release fpm 0.8.1

2023-04-10 14:59 UTC, awvwgk commented
Federico @perazz, the implicit typing is project local on purpose, such that every project on its own can decide on the needed language features.

2023-04-11 06:24 UTC, merged

2023-04-11 13:07 UTC, urbanjost commented
I am seeing 0.8.1 but "fpm update" keeps pulling the remote dependencies.

urbanjs@mercury:~/github/M_strings$ fpm --version
Version:     0.8.1, alpha
Program:     fpm(1)
Description: A Fortran package manager and build system
Home Page:   https://github.com/fortran-lang/fpm
License:     MIT
OS Type:     Linux
urbanjs@mercury:~/github/M_strings$ fpm update
# Update: M_msg
Reinitialized existing Git repository in /home/urbanjs/venus/V600/github/M_strings/build/dependencies/M_msg/.git/
remote: Enumerating objects: 275, done.
remote: Counting objects: 100% (275/275), done.
remote: Compressing objects: 100% (140/140), done.
remote: Total 275 (delta 147), reused 221 (delta 131), pack-reused 0
Receiving objects: 100% (275/275), 1.14 MiB | 4.28 MiB/s, done.
Resolving deltas: 100% (147/147), done.
From https://github.com/urbanjost/M_msg
 * branch            HEAD       -> FETCH_HEAD
urbanjs@mercury:~/github/M_strings$ fpm update
# Update: M_msg
Reinitialized existing Git repository in /home/urbanjs/venus/V600/github/M_strings/build/dependencies/M_msg/.git/
remote: Enumerating objects: 275, done.
remote: Counting objects: 100% (275/275), done.
remote: Compressing objects: 100% (140/140), done.
remote: Total 275 (delta 147), reused 221 (delta 131), pack-reused 0
Receiving objects: 100% (275/275), 1.14 MiB | 2.71 MiB/s, done.
Resolving deltas: 100% (147/147), done.
From https://github.com/urbanjost/M_msg
 * branch            HEAD       -> FETCH_HEAD